import type { CreateVehiclePayload } from '~/types'

const seedData: CreateVehiclePayload[] = [
  {
    slug: "2022-toyota-prado-tx",
    title: "2022 Toyota Prado TX",
    make: "Toyota",
    model: "Prado",
    year: 2022,
    price: 7500000,
    priceLabel: "KSh 7,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "12,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "2.8L",
    seats: 7,
    driveType: "4WD",
    colour: "White",
    condition: "used",
    description: "Pristine 2022 Toyota Prado TX, low mileage, dealer maintained. Perfect for Nairobi roads and weekend getaways.",
    features: ["Sunroof", "Leather Seats", "Reverse Camera", "Cruise Control"],
    images: ["https://images.unsplash.com/photo-1594568284297-7c64464062b1?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Toyota Prado TX for Sale | Apex Rides",
    metaDesc: "Buy a clean 2022 Toyota Prado TX in Nairobi. 12,000km, Diesel, Automatic. Inquire now."
  },
  {
    slug: "2023-toyota-land-cruiser-zx",
    title: "2023 Toyota Land Cruiser ZX",
    make: "Toyota",
    model: "Land Cruiser",
    year: 2023,
    price: 18500000,
    priceLabel: "KSh 18,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: 5000,
    transmission: "automatic",
    fuelType: "petrol",
    engine: "3.5L V6",
    seats: 7,
    driveType: "4WD",
    colour: "Black",
    condition: "used",
    description: "The ultimate luxury SUV. 2023 Land Cruiser 300 Series ZX. Full options, highest spec available.",
    features: ["Cool Box", "JBL Sound System", "Rear Entertainment", "Adaptive Suspension"],
    images: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2023 Toyota Land Cruiser 300 ZX for Sale | Apex Rides",
    metaDesc: "The new 300 series LC300 ZX. 2023 model, petrol V6. Experience luxury and power."
  },
  {
    slug: "2021-mazda-cx-5",
    title: "2021 Mazda CX-5",
    make: "Mazda",
    model: "CX-5",
    year: 2021,
    price: 3800000,
    priceLabel: "KSh 3,800,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: false,
    mileage: "35,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L",
    seats: 5,
    driveType: "2WD",
    colour: "Soul Red",
    condition: "used",
    description: "Elegant and sporty. 2021 Mazda CX-5 in the iconic Soul Red. Excellent fuel economy and premium interior.",
    features: ["Heads-up Display", "Bose Audio", "Lane Assist", "Blind Spot Monitor"],
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2021 Mazda CX-5 for Sale | Apex Rides Nairobi",
    metaDesc: "Reliable 2021 Mazda CX-5. Perfect family SUV. Soul Red Crystal color. KSh 3.8M."
  },
  {
    slug: "2022-nissan-x-trail",
    title: "2022 Nissan X-Trail",
    make: "Nissan",
    model: "X-Trail",
    year: 2022,
    price: 4200000,
    priceLabel: "KSh 4,200,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: false,
    mileage: "22,000",
    transmission: "automatic",
    fuelType: "hybrid",
    engine: "2.0L Hybrid",
    seats: 7,
    driveType: "4WD",
    colour: "Silver",
    condition: "used",
    description: "Efficient hybrid power. 2022 Nissan X-Trail Hybrid. 7-seater configuration, perfect for families.",
    features: ["360 Camera", "Panoramic Sunroof", "Power Tailgate", "Eco Mode"],
    images: ["https://images.unsplash.com/photo-1566933267-73885f27ef5c?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Nissan X-Trail Hybrid for Sale | Apex Rides",
    metaDesc: "Eco-friendly 2022 Nissan X-Trail Hybrid. 7 seats, 4WD. Competitive pricing in Nairobi."
  },
  {
    slug: "2020-mercedes-benz-c180",
    title: "2020 Mercedes-Benz C180",
    make: "Mercedes-Benz",
    model: "C180",
    year: 2020,
    price: 5200000,
    priceLabel: "KSh 5,200,000",
    categoryId: "sedan",
    category: "Sedan",
    status: "available",
    featured: true,
    mileage: "40,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "1.6L Turbo",
    seats: 5,
    driveType: "2WD",
    colour: "Iridium Silver",
    condition: "used",
    description: "Class and sophistication. 2020 C-Class Mercedes. Very clean unit with AMG line interior trim.",
    features: ["Ambient Lighting", "Digital Cockpit", "Park Assist", "Apple CarPlay"],
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2020 Mercedes-Benz C180 for Sale | Apex Rides",
    metaDesc: "Pre-owned 2020 Mercedes C180. Low mileage, full service history. Luxury sedan in Nairobi."
  },
  {
    slug: "2023-mercedes-gle-350",
    title: "2023 Mercedes GLE 350",
    make: "Mercedes-Benz",
    model: "GLE 350",
    year: 2023,
    price: 14500000,
    priceLabel: "KSh 14,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "3,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "3.0L",
    seats: 5,
    driveType: "AWD",
    colour: "Selenite Grey",
    condition: "certified-pre-owned",
    description: "Almost new 2023 Mercedes GLE 350. Modern luxury meets off-road capability. MBUX infotainment system.",
    features: ["Burmester Sound", "Heated Seats", "Air Suspension", "Active Stop-and-Go"],
    images: ["https://images.unsplash.com/photo-1606148632349-56ca3169f4b9?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2023 Mercedes-Benz GLE 350 for Sale | Apex Rides",
    metaDesc: "Current model 2023 Mercedes GLE 350. Highest spec, low mileage. Available for immediate delivery."
  },
  {
    slug: "2022-bmw-x5",
    title: "2022 BMW X5 xDrive40i",
    make: "BMW",
    model: "X5",
    year: 2022,
    price: 12800000,
    priceLabel: "KSh 12,800,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "18,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "3.0L Turbo",
    seats: 5,
    driveType: "AWD",
    colour: "Phonic Blue",
    condition: "used",
    description: "The ultimate driving machine. 2022 BMW X5 with M-Sport package. Dynamic performance and luxury.",
    features: ["M-Sport Package", "Gesture Control", "Laser Lights", "Soft Close Doors"],
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 BMW X5 M-Sport for Sale | Apex Rides",
    metaDesc: "Stunning 2022 BMW X5 xDrive40i M-Sport. Performance SUV at its best. KSh 12.8M."
  },
  {
    slug: "2021-bmw-320i",
    title: "2021 BMW 320i M-Sport",
    make: "BMW",
    model: "320i",
    year: 2021,
    price: 5800000,
    priceLabel: "KSh 5,800,000",
    categoryId: "sedan",
    category: "Sedan",
    status: "available",
    featured: false,
    mileage: "28,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L Turbo",
    seats: 5,
    driveType: "2WD",
    colour: "Alpine White",
    condition: "used",
    description: "Sporty and refined. 2021 BMW 3 Series G20. Modern tech and engaging driving dynamics.",
    features: ["Live Cockpit", "Sport Seats", "Paddle Shifters", "Harman Kardon"],
    images: ["https://images.unsplash.com/photo-1556139930-c23fa4a4f934?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2021 BMW 320i M-Sport for Sale | Apex Rides",
    metaDesc: "2021 BMW 320i G20 M-Sport. Low mileage, dealer maintained luxury sedan in Nairobi."
  },
  {
    slug: "2022-toyota-hilux-invincible",
    title: "2022 Toyota Hilux Invincible",
    make: "Toyota",
    model: "Hilux",
    year: 2022,
    price: 6500000,
    priceLabel: "KSh 6,500,000",
    categoryId: "pickup",
    category: "Pickup",
    status: "available",
    featured: true,
    mileage: "15,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "2.8L",
    seats: 5,
    driveType: "4WD",
    colour: "Oxide Bronze",
    condition: "used",
    description: "Rugged and capable. 2022 Hilux Invincible. The most durable pickup for any terrain.",
    features: ["Bed Liner", "Tow Bar", "Differential Lock", "Touchscreen Display"],
    images: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Toyota Hilux Invincible for Sale | Apex Rides",
    metaDesc: "Tough 2022 Toyota Hilux Invincible. Diesel 4WD. Best pickup for work and leisure."
  },
  {
    slug: "2023-ford-ranger-wildtrak",
    title: "2023 Ford Ranger Wildtrak",
    make: "Ford",
    model: "Ranger",
    year: 2023,
    price: 8200000,
    priceLabel: "KSh 8,200,000",
    categoryId: "pickup",
    category: "Pickup",
    status: "available",
    featured: true,
    mileage: "2,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "2.0L Bi-Turbo",
    seats: 5,
    driveType: "4WD",
    colour: "Cyber Orange",
    condition: "new",
    description: "The next generation Ranger. 2023 Wildtrak with high-tech interior and superior towing capability.",
    features: ["12-inch Screen", "Adaptive Cruise", "Zone Lighting", "B&O Audio"],
    images: ["https://images.unsplash.com/photo-1621235129676-4740f901235e?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2023 Ford Ranger Wildtrak for Sale | Apex Rides",
    metaDesc: "Next-gen 2023 Ford Ranger Wildtrak. Cyber Orange, Bi-Turbo Diesel. Pre-order/Buy now."
  },
  {
    slug: "2021-isuzu-d-max",
    title: "2021 Isuzu D-Max V-Cross",
    make: "Isuzu",
    model: "D-Max",
    year: 2021,
    price: 5500000,
    priceLabel: "KSh 5,500,000",
    categoryId: "pickup",
    category: "Pickup",
    status: "available",
    featured: false,
    mileage: "30,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "3.0L",
    seats: 5,
    driveType: "4WD",
    colour: "Valencia Orange",
    condition: "used",
    description: "Solid and reliable. 2021 D-Max V-Cross. High-spec lifestyle pickup with legendary Isuzu diesel reliability.",
    features: ["Advanced Safety", "Climate Control", "Alloy Wheels", "Leather Trim"],
    images: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2021 Isuzu D-Max V-Cross for Sale | Apex Rides",
    metaDesc: "Used 2021 Isuzu D-Max V-Cross. 3.0L Diesel, Automatic. Reliable and powerful pickup."
  },
  {
    slug: "2020-volkswagen-amarok",
    title: "2020 Volkswagen Amarok V6",
    make: "Volkswagen",
    model: "Amarok",
    year: 2020,
    price: 5900000,
    priceLabel: "KSh 5,900,000",
    categoryId: "pickup",
    category: "Pickup",
    status: "available",
    featured: false,
    mileage: "45,000",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "3.0L V6 TDI",
    seats: 5,
    driveType: "4WD",
    colour: "Indium Grey",
    condition: "used",
    description: "The pickup that drives like a car. 2020 Amarok with the powerful V6 TDI engine. Smooth and fast.",
    features: ["V6 Power", "ErgoComfort Seats", "App-Connect", "Roll Cover"],
    images: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2020 Volkswagen Amarok V6 for Sale | Apex Rides",
    metaDesc: "Fast and powerful 2020 VW Amarok V6 TDI. 3.0L Diesel. Luxury pickup experience."
  },
  {
    slug: "2022-lexus-rx350",
    title: "2022 Lexus RX 350",
    make: "Lexus",
    model: "RX 350",
    year: 2022,
    price: 8800000,
    priceLabel: "KSh 8,800,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "12,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "3.5L V6",
    seats: 5,
    driveType: "AWD",
    colour: "Sonic Quartz",
    condition: "used",
    description: "Ultimate refinement. 2022 Lexus RX 350. Silent, luxurious, and famously reliable.",
    features: ["Lexus Safety System", "Mark Levinson Audio", "Heated/Vented Seats", "Wireless Charging"],
    images: ["https://images.unsplash.com/photo-1625890213001-07d215f1c2ff?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Lexus RX 350 for Sale | Apex Rides",
    metaDesc: "Luxury 2022 Lexus RX 350 in Nairobi. Low mileage, V6 Petrol. Unmatched comfort."
  },
  {
    slug: "2023-lexus-lx600",
    title: "2023 Lexus LX 600 VIP",
    make: "Lexus",
    model: "LX 600",
    year: 2023,
    price: 28000000,
    priceLabel: "KSh 28,000,000",
    categoryId: "suv",
    category: "SUV",
    status: "reserved",
    featured: true,
    mileage: "1,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "3.5L Twin-Turbo",
    seats: 4,
    driveType: "4WD",
    colour: "Graphite Black",
    condition: "new",
    description: "The pinnacle of Japanese luxury. 2023 LX 600 VIP edition with 4-seat configuration. Executive travel.",
    features: ["VIP Seating", "Massage Seats", "Fridge", "Theatrical Sound"],
    images: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2023 Lexus LX 600 VIP for Sale | Apex Rides",
    metaDesc: "Elite 2023 Lexus LX600 VIP Edition. 4-seater luxury, twin-turbo V6. Reserved for a client."
  },
  {
    slug: "2021-audi-q5",
    title: "2021 Audi Q5 45 TFSI",
    make: "Audi",
    model: "Q5",
    year: 2021,
    price: 6500000,
    priceLabel: "KSh 6,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: false,
    mileage: "30,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L Turbo",
    seats: 5,
    driveType: "AWD",
    colour: "Mythos Black",
    condition: "used",
    description: "Modern and tech-focused. 2021 Audi Q5 facelift. Virtual cockpit and Quattro AWD for all weather.",
    features: ["Virtual Cockpit", "Quattro AWD", "Matrix LED", "S-Line Pack"],
    images: ["https://images.unsplash.com/photo-1541348263662-e0c8643c61e6?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2021 Audi Q5 for Sale | Apex Rides Nairobi",
    metaDesc: "Premium 2021 Audi Q5. Facelift model with Virtual Cockpit. Stylish SUV in Nairobi."
  },
  {
    slug: "2020-toyota-noah",
    title: "2020 Toyota Noah Si",
    make: "Toyota",
    model: "Noah",
    year: 2020,
    price: 2800000,
    priceLabel: "KSh 2,800,000",
    categoryId: "van",
    category: "Van",
    status: "available",
    featured: false,
    mileage: "60,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L",
    seats: 8,
    driveType: "2WD",
    colour: "Pearl White",
    condition: "used",
    description: "Ultimate family van. 2020 Toyota Noah Si. Spacious, economical, and reliable for school runs and trips.",
    features: ["Dual Power Doors", "Captain Seats", "Reverse Camera", "DVD Player"],
    images: ["https://images.unsplash.com/photo-1626847037657-fd3622613ce3?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2020 Toyota Noah for Sale | Apex Rides",
    metaDesc: "Family-ready 2020 Toyota Noah Si. 8 seats, dual sliding doors. Great value in Nairobi."
  },
  {
    slug: "2022-nissan-serena",
    title: "2022 Nissan Serena e-Power",
    make: "Nissan",
    model: "Serena",
    year: 2022,
    price: 3500000,
    priceLabel: "KSh 3,500,000",
    categoryId: "van",
    category: "Van",
    status: "available",
    featured: false,
    mileage: "18,000",
    transmission: "automatic",
    fuelType: "hybrid",
    engine: "1.2L e-Power",
    seats: 7,
    driveType: "2WD",
    colour: "Midnight Blue",
    condition: "used",
    description: "Revolutionary e-Power hybrid. 2022 Nissan Serena. Extremely fuel efficient and incredibly spacious.",
    features: ["e-Power Drive", "ProPilot Assist", "Foot-operated Doors", "Smart Mirror"],
    images: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Nissan Serena e-Power for Sale | Apex Rides",
    metaDesc: "Fuel efficient 2022 Nissan Serena e-Power. Hybrid van, 7 seats. High tech and comfortable."
  },
  {
    slug: "2023-range-rover-sport",
    title: "2023 Range Rover Sport Dynamic SE",
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2023,
    price: 19500000,
    priceLabel: "KSh 19,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "1,500",
    transmission: "automatic",
    fuelType: "diesel",
    engine: "3.0L D300",
    seats: 5,
    driveType: "AWD",
    colour: "Giotto Grey",
    condition: "new",
    description: "The all-new Range Rover Sport. 2023 Dynamic SE model. Unparalleled luxury and presence.",
    features: ["Soft Close", "Meridian Sound", "ClearSight View", "22-inch Wheels"],
    images: ["https://images.unsplash.com/photo-1606611013016-969c19ba27bb?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2023 Range Rover Sport for Sale | Apex Rides",
    metaDesc: "Brand new 2023 Range Rover Sport. Dynamic SE, Giotto Grey. The ultimate luxury SUV statement."
  },
  {
    slug: "2022-porsche-cayenne",
    title: "2022 Porsche Cayenne Coupe",
    make: "Porsche",
    model: "Cayenne",
    year: 2022,
    price: 15500000,
    priceLabel: "KSh 15,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: true,
    mileage: "8,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "3.0L Turbo",
    seats: 5,
    driveType: "AWD",
    colour: "Jet Black",
    condition: "used",
    description: "Sports car performance in an SUV. 2022 Porsche Cayenne Coupe. Stunning design and handling.",
    features: ["Sport Chrono", "Panoramic Roof", "Bose Audio", "PASM"],
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2022 Porsche Cayenne Coupe for Sale | Apex Rides",
    metaDesc: "Pre-owned 2022 Porsche Cayenne Coupe. Jet Black, Sport Chrono package. Thrilling luxury SUV."
  },
  {
    slug: "2021-subaru-forester",
    title: "2021 Subaru Forester EyeSight",
    make: "Subaru",
    model: "Forester",
    year: 2021,
    price: 4500000,
    priceLabel: "KSh 4,500,000",
    categoryId: "suv",
    category: "SUV",
    status: "available",
    featured: false,
    mileage: "25,000",
    transmission: "automatic",
    fuelType: "petrol",
    engine: "2.0L",
    seats: 5,
    driveType: "AWD",
    colour: "Crystal White",
    condition: "used",
    description: "Safety and capability. 2021 Subaru Forester with EyeSight technology. The safest family SUV.",
    features: ["EyeSight Driver Assist", "X-Mode", "Adaptive Cruise", "Memory Seats"],
    images: ["https://images.unsplash.com/photo-1563720223185-11003d516905?auto=format&fit=crop&q=80&w=800"],
    metaTitle: "2021 Subaru Forester EyeSight for Sale | Apex Rides",
    metaDesc: "Safe and reliable 2021 Subaru Forester. EyeSight tech, Symmetrical AWD. Available now."
  }
]

export const seedVehicles = async () => {
  const { vehicles } = await readVehicles({ limit: 1 })
  if (vehicles.length > 0) return // Already seeded
  
  console.log('Seeding vehicles...')
  for (const data of seedData) {
    await createVehicle(data)
  }
  console.log('Seeding complete.')
}
